### ISSUE TITLE
Primeira tarefa!

### ISSUE THREAD

**Issue by juanzeen** [Juanzeen/dataStrucuture1#2]
Para iniciar os trabalhos no repositório criei essa issue que acho legal a gente usar pra se comunicar, mesmo que tenhamos whatsapp e outros canais para isso, acho maneiro a gente aprender a usar esses recursos que o gitHub dá de presente pra gente. 

Planejo usar isso aqui pra podermos nos comunicar em casos de PRs negados ou simplesmente para termos uma noção do que cada um está trabalhando, então acho maneiro toda vez que a gente for começar um determinado código de alguma lista colocarmos aqui que estamos fazendo ele.

Da mesma maneira que acho bem maneiro a gente colocar aqui quando tiver com algum bug ou problema que não temos ideia de como resolver, porque também fica mais legal de visualizar e versionar nossos códigos. 

Pra cima negão!

## `lets code!`

**Comment by juanzeen** [comment]
Esqueci de falar que acho que ia ser bem maneiro a gente usar esse campo pra se comunicar em inglês, preciso muito treinar o meu e acho que é legal pra ja ir acostumando. Como é um local que provavelmente vamos olhar mais de uma vez, mesmo que não consigamos entender de primeira, tem nosso grande amigo tradutor 😄

**Comment by Filipe-Samuel-p** [comment]
hahahahah ok, I liked the ideas. Here we go
code in English too

**Comment by Juanzeen** [comment]
lets get it, little black

**Comment by juanzeen** [comment]
lets get it, little black
