### ISSUE TITLE
Organização do REPO

### ISSUE THREAD

**Issue by juanzeen** [Juanzeen/dataStrucuture1#3]
## O Repositório está funcionando da seguinte maneira:
- Não aceita push/commits direto na main;
- Só vamos conseguir upar as paradas pra cá por meio de branches separadas, que por sinal acho que podem ser criadas com os nossos nomes e usarmos sempre ou a gente cria uma branch pra cada questão que fizermos e depois de prontas a gente apaga a branch e cria outra;
- Os PRs só vão passar pra main depois que nós dois aprovarmos ele, não sei se é o mais viável, mas pelo menos pra esse começo acho legal, pois garante que nós dois vamos precisar revisar o código antes dele subir pro remoto de fato.

**Comment by Filipe-Samuel-p** [comment]
perfect!
